config/routes.rb
Welovemerthyr::Application.routes.draw do
  #match 'auth/:provider/callback' => 'subscribers#callback_facebook'
  #match 'auth/failure' => redirect('/')
  post 'auth/:provider/callback' => 'subscribers#callback_facebook'
  post 'auth/failure' => redirect('/')

  scope "public" do
    # New Subscriber
    get '/new_subscriber' => 'pages#new_subscriber', as: 'public_new_subscriber'
    post '/create_subscriber' => 'pages#create_subscriber'
    
    get '/privacy_policy' => 'pages#privacy_policy', as: 'public_privacy_policy'
    # Homepage.
    get '/front' => 'pages#front'

    # Blog index/post pages.
    get '/blog' => 'pages#blog'
    get '/blog_post/:id' => 'pages#blog_post', as: 'blog_post'

    # Events index/show pages.
    get '/events' => 'pages#events', as: 'public_events'
    get '/event/:id' => 'pages#event', as: 'public_event'

    # Vouchers index/show page.
    get '/vouchers' => 'pages#vouchers', as: 'public_vouchers'
    get '/vouchers/:id' => 'pages#voucher', as: 'public_voucher'

    # Businesses page and business page.
    get '/businesses_category/:cat' => 'pages#businesses_category', as: 'public_businesses_category'
    get '/businesses/search' => 'pages#businesses_results', as: 'public_businesses_search'
    get '/businesses/:id' => 'pages#business', as: 'public_business'

    # Static pages edit by admin.
    get '/templates/:id' => 'pages#static_page', as: 'public_static_page'

    get '/visiting' => 'pages#visiting', as: 'public_visiting'
    get '/guides' => 'pages#guides', as: 'public_guides'

    get '/update_guides_map' => 'pages#update_guides_map', as: 'update_guides_map'

    get 'pages/:id' => 'pages#public_show', as: 'public_page_show'
  end

  scope "admin" do
    resources :pages do
      get 'admin', on: :collection
    end

    resources :businesses do
      post '/invite' => 'businesses#invite', on: :member
      get '/less_active' => 'businesses#less_active', on: :collection, as: :less_active
    end

    resources :deals, path: 'vouchers'
    resources :page_templates
    resources :posts
    resources :sliders
    resources :events
    resources :business_category_templates
    resources :downloads
    resources :subscribers do
      post '/subsribe' => 'subscribers#subscribe', on: :collection
    end
    
  end

  resources :subscribers do
    post '/subsribe' => 'subscribers#subscribe', on: :collection
  end

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' }

  get '/admin' => redirect('/admin/pages/admin'), as: 'admin'

  root to: 'pages#front'

  api vendor_string: "welovemerthyr", default_version: 1 do
    version 1 do
      cache as: 'v1' do
        match :posts, to: 'posts#index', via: [:options]
        resources :posts, only:  %w(index show)

        match :events, to: 'events#index', via: [:options]
        match 'events/:id', to: 'events#show', via: [:options]
        resources :events, only:  %w(index show)

        match :deals, to: 'deals#index', via: [:options]
        match 'deals/:id', to: 'deals#show', via: [:options]
        resources :deals, only:  %w(index show)

        match :businesses, to: 'businesses#index', via: [:options]
        match 'businesses/:id', to: 'businesses#show', via: [:options]
        resources :businesses, only:  %w(index show)

        match :business_categories, to: 'businesses#index', via: [:options]
        get 'business_categories', to: "businesses#index" 

        match 'business_categories/:category', to: 'businesses#index', via: [:options]
        get 'business_categories/:category', to: "businesses#index" 

        match 'deleted_records', to: 'deleted_records#index', via: [:options]
        resources :deleted_records, only:  %w(index)
      end
    end

  end

  #redirects
  get '/facebook' => redirect('http://www.facebook.com/welovemerthyr')
  get '/twitter' => redirect('http://www.twitter.com/welovemerthyr')
  get '/xmas2014_fb' => redirect('https://www.facebook.com/events/1468240193457417')
end

app/controllers/api/v1/businesses_controller.rb
class Api::V1::BusinessesController < Api::BaseController
  PER_PAGE = 25

  ##
  # Returns paginated collection of businesses
  #
  # GET /api/v1/businesses
  #
  #. Also can filter by category.
  #
  # GET /api/v1/businesses/Shopping
  #
  # To filter by service tag, pass tag name as a query param.
  #
  # GET /api/v1/businesses/?tag=cloths
  # GET /api/v1/businesses/Shopping/?tag=cloths
  #
  # params:
  #   header - API Version
  #
  # = Examples
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/businesses
  #
  #   resp.status
  #   => 200
  #
  #   resp.body
  #   [{"id":"522e2ea69ef1ea5cdf000008","name":"4 Sure Wales","category":"Services","address":"7 Glebeland Street ",
  #   "town":"Merthyr Tydfil","postcode":"CF47 8AU","telephone":"01685 373311","website":"http://www.4surewales.co.uk", photo: ''},{ ...}]

  def index
    category  = params[:category]
    tag       = params[:tag]
    query     = params[:query]
    page      = params[:page]
    since     = params[:since]

    @businesses = Business.order_by("name asc")
    @businesses = @businesses.where(:updated_at.gte => Time.parse(since)) if since.present?
    @businesses = @businesses.where(category: category) if category.present?
    @businesses = @businesses.where(:services => /#{tag}/) if tag.present?
    @businesses = @businesses.or(services: /#{query}/i).or(name: /#{query}/i) if query.present?
    @businesses = @businesses.page(page).per(PER_PAGE) if page.present?

    respond_with @businesses
  end

  ##
  # Returns the business for the given post id
  #
  # GET /api/v1/business/564c57c8663849b587000001
  #
  # params:
  #   header - API Version
  #
  # = Examples
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/business/564c57c8663849b587000001
  #
  #   resp.status
  #   => 200
  #
  #   resp.body
  #   => {"name":"4 Sure Wales","category":"Services","contact":"Stephen Bew","address":"7 Glebeland Street ","town":"Merthyr Tydfil","postcode":"CF47 8AU","telephone":"01685 373311","website":"http://www.4surewales.co.uk","email":"steve@4surewales.co.uk","twitter":"@","facebook":false,"services":"insurance,general insurance,house insurance,car insurance,travel insurance,liability insurance,business insurance","profile":"","photo":"/uploads/business/photo/522e2ea69ef1ea5cdf000008/small_thumb_SAM_1422.JPG","coordinates":[-3.3790813,51.7465215],"zone":"Main BID","monday":"9am - 9am","tuesday":"9am - 9am","wednesday":"9am - 9am","thursday":"9am - 9am","friday":"9am - 9am","saturday":"9am - 9am","sunday":"Closed"}
  #
  #   curl -H "accept: application/vnd.welovemerthyr+json;version=1" http://localhost:5000/api/business/not_existing_record
  #
  #   resp.status
  #   => 404
  #
  #   resp.body
  #   => {"message": "Resource not found"}
  #
  
  def show
    @business = Business.find(params[:id])
    respond_with @business
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  PER_PAGE = 20

  load_and_authorize_resource

  layout 'new_admin'

  before_filter :fix_check_box, only: [:create, :update]

  def index
    @businesses = @businesses.order_by("name asc").page(params[:page]).per(PER_PAGE)

    respond_to do |format|
      #format.html # index.html.erb
      format.html { render layout: 'new_admin' }
      format.json { render json: @businesses }
    end
  end

  def show
    respond_to do |format|
      # format.html # show.html.erb
      format.html { render layout: 'new_admin' }
      format.json { render json: @business }
    end
  end

  def new
    respond_to do |format|
      # format.html # new.html.erb
      format.html { render layout: 'new_admin' }
      format.json { render json: @business }
    end
  end

  def create
    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render json: @business, status: :created, location: @business }
      else
        format.html { render action: "new" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @business.update_attributes(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def invite
    Notifier.invitation_to_business(params[:email], @business).deliver
    redirect_to business_path(@business), notice: 'Invitations sent.'
  end

  def less_active
    @less_active_businesses = Business.where(:updated_at.lte => 6.month.ago).order_by(updated_at: :asc)
  end

private

  def fix_check_box
    params[:business].merge!(facebook: 0) unless params[:business].has_key?(:facebook)
  end

  def business_params
    params.require(:business).permit(:name, :category, :contact, :address, :town, :postcode, :telephone, :website, :email,
    :twitter, :facebook, :services, :profile, :photo, :remove_photo,
    :monday_opening, :monday_closing, :tuesday_opening, :tuesday_closing,
    :wednesday_opening, :wednesday_closing, :thursday_opening,
    :thursday_closing, :friday_opening, :friday_closing, :saturday_opening,
    :saturday_closing, :sunday_opening, :sunday_closing, :zone)
  end

end

app/helpers/api/v1/businesses_helper.rb
module Api::V1::BusinessesHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
  def infowindow_single(b)
    info = ""

    info << "<b>#{b.name}</b>"
    info << "<br />"
    info << b.full_address
    info << "<br />"
    info << "Telephone: #{b.telephone}"

    info
  end

  def infowindow_multiple(b)
    info = ""

    info << "<div class='col-lg-12'>"

    if b.photo.present?
      info << "<div class='col-lg-4'>"
      info << "<image src='#{b.photo_url(:small_thumb)}' />"
      info << "</div>"
    end

    info << "<div class='col-lg-8'>"
    info << "<b><a href='#{public_business_path(b)}'>#{b.name}</a></b>"
    info << "<br />"
    info << "<small>"
    info << "<b>Services</b>: #{b.services.split(',').join(', ')}"
    info << "<br />"
    info << "<b>Address</b>: #{b.full_address}"
    info << "<br />"
    info << "<b>Telephone</b>: #{b.telephone}"
    info << "</small>"
    info << "</div>"
    info << "</div>"

    info
  end
end

app/views/businesses/_form.html.erb
<div class="row animated fadeInUp">
  <div class="col-sm-12">
    <div class="panel">
      <div class="panel-content">
        <div class="row">
          <div class="col-md-12">
            <%= simple_form_for @business, html: { class: 'form-horizontal'}, defaults: { input_html: { class: 'form-control' }} do |f| %>
              <div class="form-group">
                <label for="name" class="col-sm-3 control-label">Name<span class="require">*</span></label>
                <div class="col-sm-6">
                  <%= f.input :name, label: false %>
                </div>
              </div>  
              <div class="form-group">
                <label for="category" class="col-sm-3 control-label">Category</label>
                <div class="col-sm-6">
                  <%= f.input :category, collection: Business::CATEGORIES, prompt: 'Please select', label: false %>
                </div>
              </div>  
              <div class="form-group">
                <label for="contact" class="col-sm-3 control-label">Contact</label>
                <div class="col-sm-6">
                  <%= f.input :contact, label: false %>
                </div>
              </div>  
              <div class="form-group">
                <label for="address" class="col-sm-3 control-label">Address</label>
                <div class="col-sm-6">
                  <%= f.input :address, label: false %>       
                </div>
              </div>  
              <div class="form-group">
                <label for="town" class="col-sm-3 control-label">Town</label>
                <div class="col-sm-6">
                  <%= f.input :town, placeholder: Business::DEFAULT_TOWN, label: false %>
                </div>
              </div>  
              <div class="form-group">
                <label for="postcode" class="col-sm-3 control-label">Postcode</label>
                <div class="col-sm-6">
                  <%= f.input :postcode, label: false %>
                </div>
              </div>  
              <div class="form-group">
                <label for="telephone" class="col-sm-3 control-label">Telephone</label>
                <div class="col-sm-6">
                  <%= f.input :telephone, label: false %>
                </div>
              </div>  
              <div class="form-group">
                <label for="website" class="col-sm-3 control-label">Website</label>
                <div class="col-sm-6">
                  <%= f.input :website, label: false %>
                </div>
              </div>  
              <div class="form-group">
                <label for="email" class="col-sm-3 control-label">Email</label>
                <div class="col-sm-6">
                  <%= f.input :email, label: false %>
                </div>
              </div>            
              <div class="form-group">
                <label for="twitter" class="col-sm-3 control-label">Twitter</label>
                <div class="col-sm-6">
                  <%= f.input :twitter, label: false -%>
                </div>
              </div>            
              <div class="form-group">
                <%= f.hidden_field :lat%>
                <%= f.hidden_field :lon%>         
              </div>            
              <div class="form-group">
                <label for="business_facebook" class="col-sm-3 control-label">Facebook</label>
                <div class="col-sm-6">
                  <div class="checkbox">
                    <input type="checkbox" id="business_facebook" name="business[facebook]" class="boolean optional" value="1" <%= "checked=checked" if @business.facebook %> />
                  </div>
                </div>
              </div>            
              <div class="form-group">
                <label for="services" class="col-sm-3 control-label">Services</label>
                <div class="col-sm-6">
                  <%= f.input :services, label: false -%>
                </div>
              </div>         
              <div class="form-group">
                <label for="Profile" class="col-sm-3 control-label">Profile</label>
                <div class="col-sm-6">
                  <%= f.input :profile, as: :text, input_html: { class: 'my_tinymce' }, label: false -%>
                </div>
              </div>
              <%- if @business.photo.present? -%>
                <div class="form-group">
                  <label class="col-sm-3 control-label"></label>
                  <div class="col-sm-6">
                    <%= image_tag @business.photo_url(:admin_thumb) -%>
                  </div>
                </div>
                <div class='form-group'>
                  <label class="col-lg-2 control-label" for="business_remove_image"></label>
                  <div class="col-lg-10">
                    <div class="checkbox">
                      <input type="checkbox" id="business_remove_photo" name="business[remove_photo]" class="boolean optional" value="1" />
                      <label for="business_remove_photo">Remove photo</label>
                    </div>
                  </div>
                </div>
              <% end %>              
              <div class="form-group">
                <label for="photo" class="col-sm-3 control-label">Photo</label>
                <div class="col-sm-6">
                  <%= f.input :photo, label: false -%>
                </div>
              </div> 
              <%- Business::DAYS.each do |day| -%>
                <div class="form-group">
                  <label for="#{day}_opening" class="col-sm-3 control-label"><%= day %>_opening</label>
                  <div class="col-sm-6">
                    <%= f.input "#{day}_opening", collection: Business::TIMES, prompt: 'Please select', required: false, include_blank: true, label: false -%>
                  </div>
                </div>  
                <div class="form-group">
                  <label for="#{day}_closing" class="col-sm-3 control-label"><%= day %>_closing</label>
                  <div class="col-sm-6">
                    <%= f.input "#{day}_closing", collection: Business::TIMES, prompt: 'Please select', required: false, include_blank: true, label: false -%>
                  </div>
                </div>                 
              <%- end -%>
              <div class="form-group">
                <label for="zone" class="col-sm-3 control-label">Zone</label>
                <div class="col-sm-6">
                  <%= f.input :zone, collection: Business::ZONES, include_blank: false, label: false -%>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-3 col-sm-9">
                  <%= f.button :submit, class: 'btn-primary' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/businesses/edit.html.erb
<div class="content">
  <h4 class="section-subtitle"><b>Edit</b> business</h4>
  <!-- content HEADER -->
  <!-- ========================================================= -->
  <div class="content-header">
   <!-- leftside content header -->
    <div class="leftside-content-header">
     <ul class="breadcrumbs">
       <li><i class="fa fa-columns" aria-hidden="true"></i><a href="#">Business</a> <a href="#">Edit</a></li>
     </ul>
    </div>
  </div>
  <%= render 'form' %>
  <%= render partial: 'shared/business_update_script'-%>
  <%= link_to 'Show', @business %> |
  <%= link_to 'Back', businesses_path %>
</div>

app/views/businesses/index.html.erb
<div class="content">
  <!-- content HEADER -->
  <!-- ========================================================= -->
  <div class="content-header">
    <!-- leftside content header -->
    <div class="leftside-content-header">
      <ul class="breadcrumbs">
        <li class="active-item"><a href="#">Businesses</a></li>
      </ul>
    </div>
  </div>
  <div class="row animated fadeInRight">
    <div class="col-sm-12">
      <h4 class="section-subtitle"><b>Listing</b> businesses</h4>
      <p> 
        <%= link_to('New Business', new_business_path) if can?(:new, Business) %> |
        <%= link_to('Less Active', less_active_businesses_path) if can?(:new, Business) %> 
      </p>
      <div class="panel">
        <div class="panel-content">
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Category</th>
                  <th>Contact</th>
                  <th>Telephone</th>
                  <th>Zone</th>
                  <%- if can?(:edit, Business) -%>
                    <th>Actions</th>
                  <%- end -%>
                </tr>
              </thead>
              <tbody>
                <% @businesses.each do |business| %>
                  <tr>
                    <td><%= business.name %></td>
                    <td><%= business.category %></td>
                    <td><%= business.contact %></td>
                    <td><%= business.telephone %></td>
                    <td><%= business.zone %></td>
                    <%- if can?(:edit, Business) -%>
                      <td>
                        <div class="btn-group btn-group-xs">
                          <%= link_to business, id: "logo" do %>
                            <i class="fa fa-eye"></i>
                          <% end %>
                          <%= link_to edit_business_path(business), id: "logo" do %>
                            <i class="fa fa-pencil"></i>
                          <% end %>
                          <% if can?(:destroy, Business) %>
                            <%= link_to business, method: :delete, data: { confirm: 'Are you sure?' }, id: "logo" do %>
                              <i class="fa fa-times"></i>
                            <% end %>
                          <%end %>
                        </div>
                      </td>
                    <%- end -%>
                  </tr>
              <% end %>
              </tbody>
            </table>
            <%= paginate @businesses -%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/businesses/less_active.html.erb
<div class="content">
  <!-- content HEADER -->
  <!-- ========================================================= -->
  <div class="content-header">
    <!-- leftside content header -->
    <div class="leftside-content-header">
      <ul class="breadcrumbs">
        <li><i class="fa fa-columns" aria-hidden="true"></i><a href="#">Less active businesses</a></li>
      </ul>
    </div>
  </div>
  <div class="row animated fadeInRight">
    <div class="col-sm-12">
      <h1>Less active businesses</h1>
      <p>
        These businesses haven't been modified for 6 months.
      </p>
      <p>
        Showing <%= pluralize(@less_active_businesses.size, 'business') %>
      </p>
      <div class="panel">
        <div class="panel-content">
          <div class="table-responsive">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Category</th>
                  <th>Contact</th>
                  <th>Telephone</th>
                  <th>Last modified</th>
                </tr>
              </thead>
              <tbody>
                <% @less_active_businesses.each do |business| %>
                  <tr>
                    <td><%= link_to business.name, business %></td>
                    <td><%= business.category %></td>
                    <td><%= business.contact %></td>
                    <td><%= business.telephone %></td>
                    <td>
                      <% if business.updated_at %>
                      <%= business.updated_at.strftime('%Y-%b-%d')  %>
                      <% elsif business.created_at %>
                      <%= business.created_at.strftime('%Y-%b-%d')  %>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>
              </tbody>
            </table>
          </div>
        </div>  
      </div>
    </div>
  </div>  
</div>

app/views/businesses/new.html.erb
<div class="content">
  <h4 class="section-subtitle"><b>New</b> business</h4>
  <!-- content HEADER -->
  <!-- ========================================================= -->
  <div class="content-header">
   <!-- leftside content header -->
    <div class="leftside-content-header">
     <ul class="breadcrumbs">
       <li><i class="fa fa-columns" aria-hidden="true"></i><a href="#">Business</a> <a href="#">New</a></li>
     </ul>
    </div>
  </div>
  <%= render 'form' %>

  <%= link_to 'Back', businesses_path %>
</div>

app/views/businesses/show.html.erb
<div class="content">
  <!-- content HEADER -->
  <!-- ========================================================= -->
  <div class="content-header">
    <!-- leftside content header -->
    <div class="leftside-content-header">
      <ul class="breadcrumbs">
        <li><i class="fa fa-columns" aria-hidden="true"></i><a href="#">Businesses</a></li>
        <li><a>Show</a></li>
      </ul>
    </div>
  </div>
  <div class="row animated fadeInRight">
    <div class="col-sm-12">
      <% unless notice.blank? %>
        <p id="notice" class="alert alert-success"><%= notice %></p>
      <% end %>
      <div class="panel">
        <div class="panel-content">
          <div class="table-responsive">            
            <p>
              <%- if @business.user? -%>
            <p>
              <b>User:</b>
              <%= @business.user.email %>
            </p>
          <%- else -%>
            <div class="row">
              <div class="well col-lg-6">
                <%= form_tag invite_business_path(@business), class: 'form-horizontal' do -%>
                  <div class='form-group'>
                    <div class='control-label col-lg-2'>
                      <%= label_tag :email, 'Email' -%>
                    </div>
                    <div class="col-lg-10">
                      <%= text_field_tag :email, nil, { class: 'form-control col-lg-3' } -%>
                    </div>
                  </div>
                  <div class='form-group'>
                    <div class='control-label col-lg-2'>
                      <%= label_tag :email, '' -%>
                    </div>
                    <div class="col-lg-10">
                      <%= submit_tag 'Invite', class: 'btn btn-primary btn-sm' -%>
                    </div>
                  </div>
                <%- end -%>
              </div>
            </div>
          <%- end -%>

          <p>
            <b>Name:</b>
            <%= @business.name %>
          </p>

          <p>
            <b>Category:</b>
            <%= @business.category %>
          </p>

          <p>
            <b>Contact:</b>
            <%= @business.contact %>
          </p>

          <p>
            <b>Address:</b>
            <%= @business.address %>
          </p>

          <p>
            <b>Town:</b>
            <%= @business.town %>
          </p>

          <p>
            <b>Postcode:</b>
            <%= @business.postcode %>
          </p>

          <p>
            <b>Telephone:</b>
            <%= @business.telephone %>
          </p>

          <p>
            <b>Website:</b>
            <%= @business.website %>
          </p>

          <p>
            <b>Email:</b>
            <%= @business.email %>
          </p>

          <p>
            <b>Twitter:</b>
            <%= @business.twitter %>
          </p>

          <p>
            <b>Facebook:</b>
            <%= @business.facebook %>
          </p>

          <p>
            <b>Services:</b>
            <%= @business.services %>
          </p>

          <p>
            <b>Profile:</b>
            <%=sanitize @business.profile %>
          </p>

          <p>
            <b>Photo:</b>
            <%= image_tag(@business.photo_url(:admin_thumb)) if @business.photo.present? %>
          </p>

          <p>
            <b>Lat/Lon:</b>
            <%= @business.lat -%> / <%= @business.lon -%>
          </p>

          <p>
            <%- Business::DAYS.each do |day| -%>
              <%= "#{day.capitalize} opening: #{@business.send("#{day}_opening")}" -%>
              <br />
              <%= "#{day.capitalize} closing: #{@business.send("#{day}_closing")}" -%>
              <br />
            <%- end -%>
          </p>

          <p>
            <b>Zone:</b>
            <%= @business.zone -%>
          </p>

          <%= link_to 'Create Deal', new_deal_path(business_id: @business.id), class: 'btn btn-primary' -%>
          <br />
          <br />
          <%= link_to 'Edit', edit_business_path(@business) %> |
          <%= link_to 'Back', businesses_path %>

          </div>
        </div>
      </div>
    </div> 
  </div> 
</div>